import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import env from "../config/env";
import GeneratingOverlay from "../components/GeneratingOverlay";
import TripResultView from "../components/TripResultView";
import { generateTripPlan } from "../services/tripService";

const PlannerPage = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const hasAutoGeneratedFromQuery = useRef(false);

  const [form, setForm] = useState({
    prompt: "",
    destination: "",
    budget: "",
    days: "",
    travelers: "",
    travelStyle: "",
  });
  const [loading, setLoading] = useState(false);
  const [generatedTrip, setGeneratedTrip] = useState(null);
  const [autoSaved, setAutoSaved] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const onChange = (key, value) => setForm((prev) => ({ ...prev, [key]: value }));

  const generateFromPayload = async (payload) => {
    if (!payload.prompt?.trim()) {
      setError("Please enter a trip prompt.");
      return;
    }

    setError("");
    setMessage("");
    setAutoSaved(false);
    setLoading(true);

    try {
      const { generatedTrip: trip, autoSaved: wasAutoSaved } = await generateTripPlan(payload);
      setGeneratedTrip(trip);
      setAutoSaved(Boolean(wasAutoSaved));
      if (wasAutoSaved) {
        setMessage("Trip generated and automatically saved to Saved Trips.");
      }
    } catch (err) {
      setError(err.response?.data?.message || "Could not generate trip.");
    } finally {
      setLoading(false);
    }
  };

  const onGenerate = async (event) => {
    event.preventDefault();
    await generateFromPayload(form);
  };

  useEffect(() => {
    if (hasAutoGeneratedFromQuery.current) return;

    const params = new URLSearchParams(location.search);
    const promptFromQuery = params.get("prompt") || "";
    const shouldAutoGenerate = params.get("autogenerate") === "1";

    if (!promptFromQuery) return;

    const nextForm = {
      prompt: promptFromQuery,
      destination: params.get("destination") || "",
      budget: params.get("budget") || "",
      days: params.get("days") || "",
      travelers: params.get("travelers") || "",
      travelStyle: params.get("travelStyle") || "",
    };

    setForm(nextForm);
    hasAutoGeneratedFromQuery.current = true;

    if (shouldAutoGenerate) {
      generateFromPayload(nextForm).finally(() => {
        navigate("/planner", { replace: true });
      });
    }
  }, [location.search, navigate]);

  const fieldClass =
    "neon-input w-full px-3 py-2.5 text-sm outline-none transition focus:border-cyan-300/70 focus:shadow-[0_0_22px_rgba(34,211,238,0.22)]";

  return (
    <div className="relative">
      <GeneratingOverlay open={loading} />

      <motion.section
        initial={{ opacity: 0, y: 14 }}
        animate={{ opacity: 1, y: 0 }}
        className="neon-panel p-6"
      >
        <h1 className="font-['Space_Grotesk'] text-3xl font-bold text-slate-100">Main Planner Dashboard</h1>
        <p className="mt-2 text-sm text-slate-400">Describe your ideal journey and let the travel AI orchestrate every detail.</p>

        <form onSubmit={onGenerate} className="mt-5 space-y-4">
          <textarea
            rows={5}
            value={form.prompt}
            onChange={(e) => onChange("prompt", e.target.value)}
            placeholder={env.plannerPromptPlaceholder}
            className="neon-input w-full rounded-3xl px-4 py-3 text-sm outline-none transition focus:border-cyan-300/70 focus:shadow-[0_0_24px_rgba(34,211,238,0.25)]"
          />

          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            <input className={fieldClass} placeholder="Destination" value={form.destination} onChange={(e) => onChange("destination", e.target.value)} />
            <input className={fieldClass} placeholder="Budget" value={form.budget} onChange={(e) => onChange("budget", e.target.value)} />
            <input className={fieldClass} placeholder="Days" value={form.days} onChange={(e) => onChange("days", e.target.value)} />
            <input className={fieldClass} placeholder="Travelers" value={form.travelers} onChange={(e) => onChange("travelers", e.target.value)} />
            <input className={fieldClass} placeholder="Travel style" value={form.travelStyle} onChange={(e) => onChange("travelStyle", e.target.value)} />
          </div>

          <div className="flex flex-wrap gap-3">
            <button
              type="submit"
              disabled={loading}
              className="neon-btn inline-flex items-center gap-2 text-sm disabled:cursor-not-allowed disabled:opacity-60"
            >
              <Sparkles size={16} />
              {loading ? "Generating..." : "Generate Trip"}
            </button>
            {generatedTrip && autoSaved ? (
              <span className="neon-input inline-flex items-center px-4 py-2 text-sm font-medium text-emerald-300">
                Auto-saved to Saved Trips
              </span>
            ) : null}
          </div>
        </form>

        {error && <p className="mt-3 text-sm text-rose-300">{error}</p>}
        {message && <p className="mt-3 text-sm text-emerald-300">{message}</p>}
      </motion.section>

      <TripResultView trip={generatedTrip} />
    </div>
  );
};

export default PlannerPage;
